repos:
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.4
  hooks:
    - id: poetry-check
    - id: poetry-lock
    - id: poetry-export
    - id: poetry-install

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-ast
    - id: check-added-large-files
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: check-shebang-scripts-are-executable
    - id: mixed-line-ending
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
    - id: bandit
